# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM uber.bronze.silver_obt

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from uber.bronze.dim_location

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from uber.bronze.rides_raw
